extends Node

signal tile_selected
signal tile_alt_selected
signal tile_entered
signal tile_exited
signal tile_focused
signal tile_unfocused
signal tile_targeted
signal tile_untargeted

signal character_selected
signal character_entered
signal character_exited
signal character_focused
signal character_unfocused
signal character_moving
signal character_moved

signal crystal_selected
signal crystal_alt_selected
signal crystal_entered
signal crystal_exited
signal crystal_created
signal crystal_broken

signal entity_pushed
signal entity_dropping
signal entity_dropped
